name: SentinelleFocus
options:
  bundleIdPrefix: com.dgiego38
targets:
  SentinelleFocus:
    type: application
    platform: iOS
    deploymentTarget: "17.4"
    sources: [SentinelleFocus]
    settings:
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      CODE_SIGN_ENTITLEMENTS: SentinelleFocus.entitlements
    dependencies:
      - target: SentinelleShield
      - target: SentinelleLiveActivity

  SentinelleShield:
    type: app-extension # On utilise le type générique
    platform: iOS
    sources: [ShieldExtension]
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.dgiego38.sentinellefocus.shield

  SentinelleLiveActivity:
    type: app-extension
    platform: iOS
    sources: [LiveActivityExtension]
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.dgiego38.sentinellefocus.liveactivity