name: iOS Build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install XcodeGen
        run: brew install xcodegen
      - name: Generate Project
        run: xcodegen generate
      - name: Build
        run: xcodebuild -scheme SentinelleFocus -sdk iphonesimulator build