name: iOS Build
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Build Application (No Sign)
        run: |
          xcodebuild -scheme SentinellePro \
          -sdk iphoneos \
          -configuration Debug \
          -derivedDataPath build \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          AD_HOC_CODE_SIGNING_ALLOWED=YES \
          build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SentinellePro-Debug-App
          path: build/Build/Products/Debug-iphoneos/SentinellePro.app